import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="md:p-10">
        <Navbar />
        <h1 className="my-0 py-0 md:text-xl text-center"><Link href="https://www.instagram.com/expanthree._smansa/">@expanthree._smansa</Link></h1>
        {children}
      </body>
    </html>
  );
}
